name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@main
    - name: Publish
      run: scala-cli publish . --power --secret-key env:PUBLISH_SECRET_KEY --secret-key-password env:PUBLISH_SECRET_KEY_PASSWORD --user env:PUBLISH_USER --password env:PUBLISH_PASSWORD
      env:
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
